# Generated by Django 5.2.13 on 2026-04-28 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0016_confidentiality_to_tlp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodIncidentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase1_started', models.DateTimeField(blank=True, null=True, verbose_name='Phase 1 Start')),
                ('phase1_completed', models.DateTimeField(blank=True, null=True, verbose_name='Phase 1 End')),
                ('is_false_positive', models.BooleanField(default=False, verbose_name='Is False Positive')),
                ('false_positive_reason', models.TextField(blank=True, verbose_name='Reason if False Positive')),
                ('escalated_to_l2', models.BooleanField(default=False, verbose_name='Escalated to L2')),
                ('l2_assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='L2 Assignment Time')),
                ('phase2_started', models.DateTimeField(blank=True, null=True, verbose_name='Phase 2 Start')),
                ('playbook_used', models.CharField(blank=True, max_length=150, verbose_name='Applied Playbook')),
                ('custom_containment_actions', models.TextField(blank=True, verbose_name='Custom Containment Actions')),
                ('localized_at', models.DateTimeField(blank=True, null=True, verbose_name='Containment Completed')),
                ('phase3_started', models.DateTimeField(blank=True, null=True, verbose_name='Phase 3 Start')),
                ('recovery_plan', models.TextField(blank=True, verbose_name='Recovery Plan')),
                ('recovery_verified', models.BooleanField(default=False, verbose_name='Recovery Verified')),
                ('recovered_at', models.DateTimeField(blank=True, null=True, verbose_name='Recovery Completed')),
                ('phase4_started', models.DateTimeField(blank=True, null=True, verbose_name='Phase 4 Start')),
                ('lessons_learned', models.TextField(blank=True, verbose_name='Lessons Learned')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommendations')),
                ('improvements_implemented', models.BooleanField(default=False, verbose_name='Improvements Implemented')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Official Closure Time')),
                ('sla_deadline', models.DateTimeField(blank=True, null=True, verbose_name='SLA Deadline')),
                ('sla_breached', models.BooleanField(default=False, verbose_name='SLA Breached')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='method_data', to='incidents.incident', verbose_name='Incident')),
                ('ir_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_method_incidents', to=settings.AUTH_USER_MODEL, verbose_name='IR Manager')),
            ],
            options={
                'verbose_name': 'Incident Method Data',
                'verbose_name_plural': 'Incident Method Data',
                'ordering': ['-incident__date'],
            },
        ),
    ]
