# Generated by Django 5.2.13 on 2026-04-28 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_method_extension', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='methodincidentdata',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('l1_monitoring', 'Первая линия мониторинга'), ('l2_monitoring', 'Вторая линия мониторинга'), ('security_dept', 'Департамент ИБ (ДИБ)'), ('it_dept', 'Департамент ИТ (ДИТ)'), ('security_analyst', 'Аналитик ИБ'), ('ir_manager', 'IR-менеджер'), ('management', 'Руководство/Заказчик'), ('external_expert', 'Сторонний эксперт')], max_length=30, null=True, verbose_name='Назначенная роль'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_method_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный исполнитель'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='phase2_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 2 End'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='phase3_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 3 End'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='phase4_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 4 End'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='role_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время назначения роли'),
        ),
    ]
