# Generated by Django 5.2.13 on 2026-04-28 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_method_extension', '0002_methodincidentdata_assigned_role_and_more'),
        ('incidents', '0016_confidentiality_to_tlp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='methodincidentdata',
            name='playbook_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Playbook Completed At'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='playbook_notes',
            field=models.TextField(blank=True, verbose_name='Playbook Execution Notes'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='playbook_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Playbook Started At'),
        ),
        migrations.AlterField(
            model_name='methodincidentdata',
            name='assigned_role',
            field=models.CharField(blank=True, choices=[('l1_monitoring', 'L1 Monitoring'), ('l2_monitoring', 'L2 Monitoring'), ('security_dept', 'Security Department'), ('it_dept', 'IT Department'), ('security_analyst', 'Security Analyst'), ('ir_manager', 'IR Manager'), ('management', 'Management/Client'), ('external_expert', 'External Expert')], max_length=30, null=True, verbose_name='Assigned Role'),
        ),
        migrations.AlterField(
            model_name='methodincidentdata',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_method_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='methodincidentdata',
            name='role_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Role Assigned At'),
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Playbook Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phase', models.PositiveSmallIntegerField(choices=[(1, 'Phase 1: Detection & Analysis'), (2, 'Phase 2: Damage Containment'), (3, 'Phase 3: Eradication & Recovery'), (4, 'Phase 4: Post-Incident Analysis')], verbose_name='Applicable Phase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbooks', to='incidents.incidentcategory', verbose_name='Incident Category')),
            ],
            options={
                'verbose_name': 'Playbook',
                'verbose_name_plural': 'Playbooks',
                'ordering': ['category', 'phase', 'name'],
            },
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='applied_playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_incidents', to='fir_method_extension.playbook', verbose_name='Applied Playbook'),
        ),
        migrations.CreateModel(
            name='PlaybookStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Step Order')),
                ('title', models.CharField(max_length=200, verbose_name='Step Title')),
                ('instruction', models.TextField(verbose_name='Instruction')),
                ('expected_outcome', models.TextField(blank=True, verbose_name='Expected Outcome')),
                ('reference_url', models.URLField(blank=True, verbose_name='Reference URL')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='fir_method_extension.playbook', verbose_name='Playbook')),
            ],
            options={
                'verbose_name': 'Playbook Step',
                'verbose_name_plural': 'Playbook Steps',
                'ordering': ['order'],
                'unique_together': {('playbook', 'order')},
            },
        ),
    ]
