# Generated by Django 5.2.13 on 2026-04-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_method_extension', '0003_methodincidentdata_playbook_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='methodincidentdata',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted At'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_method_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
        migrations.CreateModel(
            name='PlaybookStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Executed At')),
                ('notes', models.TextField(blank=True, verbose_name='Execution Notes')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Executed By')),
                ('incident_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='fir_method_extension.methodincidentdata', verbose_name='Incident Data')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fir_method_extension.playbookstep', verbose_name='Step')),
            ],
            options={
                'verbose_name': 'Step Execution',
                'verbose_name_plural': 'Step Executions',
                'ordering': ['step__order'],
                'unique_together': {('incident_data', 'step')},
            },
        ),
    ]
