# Generated by Django 5.2.13 on 2026-04-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_method_extension', '0004_methodincidentdata_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodincidentdata',
            name='analyst_notes',
            field=models.TextField(blank=True, help_text='Additional observations, findings, or context added during incident handling', verbose_name='Analyst Notes'),
        ),
        migrations.AddField(
            model_name='methodincidentdata',
            name='notes_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notes Last Updated'),
        ),
    ]
